language: nix
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - name: test

jobs:
  include:

    - name: "Bazel"
      script:
        - ./scripts/ci-jobs.sh bazel

    - name: "Format"
      script:
        - ./scripts/ci-jobs.sh format

    - name: "Test"
      script:
        - ./scripts/ci-jobs.sh test

    - name: "Coverage"
      script:
        - ./scripts/ci-jobs.sh coverage

    - name: "Readme / Docs"
      script:
        - ./scripts/ci-jobs.sh readme

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
  - |
    if [ ! "$(ls -A $HOME/nix-cache)" ]; then
      cp -a /nix/* $HOME/nix-cache
    fi

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/nix-cache

before_install:
  - git fetch --tags

install: |
  if [ "$(ls -A $HOME/nix-cache)" ]; then
    sudo rm -rf /nix/*
    cp -a $HOME/nix-cache/* /nix
  fi
